import { BusinessRule } from '@servicenow/sdk/core'

BusinessRule({
    $id: Now.ID['ai_summary_engine_br'],
    name: 'LEVER - AI Clinical Summary Engine',
    table: 'x_1996578_projec_0_regional_referral',
    active: true,
    when: 'async',
    action: ['insert', 'update'],
    condition: "(current.u_clinical_notes.changes() || current.u_ai_summary_source.changes()) && current.u_ai_summary_source != 'none'",
    order: 100,
    description: 'Calls Gemini or Groq REST Messages to summarize clinical notes asynchronously.',
    script: `
(function executeRule(current, previous /*null when async*/) {
    var source = current.getValue('u_ai_summary_source');
    var notes = current.getValue('u_clinical_notes');
    
    if (!notes) return;

    if (source === 'mock') {
        current.setValue('u_ai_clinical_summary', 'MOCK SUMMARY: Patient requires immediate attention. ' + notes.substring(0, 50) + '...');
        current.update();
        return;
    }

    function fetchSummary(engineName, notesText) {
        var rm = new sn_ws.RESTMessageV2(engineName, 'Generate Summary'); 
        var promptText = "You are a clinical AI. Please summarize the following patient notes for an emergency hand-off:\\n\\n" + notesText;
        var safeNotes = JSON.stringify(promptText).slice(1, -1);
        rm.setStringParameterNoEscape('doctor_notes', safeNotes);
        rm.setHttpTimeout(15000);
        var response = rm.execute();
        return {
            status: response.getStatusCode(),
            body: response.getBody()
        };
    }

    try {
        var primaryEngine = source === 'groq' ? 'Groq Triage Engine' : 'Gemini Triage Engine';
        var fallbackEngine = source === 'groq' ? 'Gemini Triage Engine' : 'Groq Triage Engine';
        var activeSource = source;
        
        gs.info('LEVER AI Engine triggered for ' + primaryEngine + '. Notes length being sent: ' + notes.length);
        var apiResponse = fetchSummary(primaryEngine, notes);
        
        // Fallback condition: If primary fails, immediately try the secondary engine
        if (apiResponse.status !== 200) {
            gs.warn('LEVER AI Engine: ' + primaryEngine + ' failed (' + apiResponse.status + '). Falling back to ' + fallbackEngine);
            apiResponse = fetchSummary(fallbackEngine, notes);
            activeSource = source === 'groq' ? 'gemini' : 'groq'; // Swap the source tracker
        }
        
        if (apiResponse.status === 200) {
            var parsed = JSON.parse(apiResponse.body);
            var summary = activeSource === 'groq' ? parsed.choices[0].message.content : parsed.candidates[0].content.parts[0].text;
            
            // If a fallback occurred, update the dropdown and add a note to the summary
            if (activeSource !== source) {
                current.setValue('u_ai_summary_source', activeSource);
                summary = "[Generated by Fallback Engine: " + activeSource.toUpperCase() + "]\\n\\n" + summary;
            }
            
            current.setValue('u_ai_clinical_summary', summary);
            current.update();
        } else {
            // Both engines failed
            gs.error('LEVER AI Engine Error (Both engines failed). Last status: ' + apiResponse.status + ' - ' + apiResponse.body);
        }
    } catch(ex) {
        gs.error('LEVER AI Engine Exception: ' + ex.message);
    }
})(current, previous);
`
})
